### ISSUE TITLE
too many arguments

### ISSUE THREAD

**Issue by fbartels** [cghdev/owncloud-dl#2]
Hi,

just gave your program a quick spin and got the following output:

```
$ LANG=en_US.UTF-8 ./cloud-dl -l
./cloud-dl: line 13: [: too many arguments

/
..
```

Did not yet have a deeper look how this could be fixed, but maybe you know right away. Apart from the error output it seems to work (at least listing is not affected by this).

Edit: cannot say with certainty which version of Nextcloud is used, but it must be some 13.x

**Comment by fbartels** [comment]
this is the error when run with `bash -x`:

```
/d:status></d:propstat><d:propstat><d:prop><d:quota-used-bytes/><d:quota-available-bytes/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>'
+ quota='-3
0
-3'
+ '[' -z ']'
+ '[' '!' -z -3 0 -3 ']'
./cloud-dl: Zeile 13: [: Zu viele Argumente.
+ echo
```

**Comment by cghdev** [comment]
Thanks @fbartels. I'll take a look.
What OS are you using?

**Comment by fbartels** [comment]
Thanks @cghdev ,

This is a system with Ubuntu 16.04.

It seems to come down to that parse_xml returns 
```
-3
0
-3
```
for my quota (which is acutal unlimited) and since in https://github.com/cghdev/cloud-dl/blob/master/cloud-dl#L13 the variable is not quoted, the "too many arguments" is thrown. Just quoting it is only have the solution, since the value is not a number and therefore cannot be compared in https://github.com/cghdev/cloud-dl/blob/master/cloud-dl#L14

**Comment by cghdev** [comment]
The issue seems to be related with the user not being able to see the quota available (it returns a 404 error).
Thanks for reporting that, I'll handle that error when I get a chance.

Edit: Never mind, that 404 was not related I believe. Indeed it returns -3, I think when quota is unlimited. It seems to work fine on my environment, but I'll do some tests and parse the returned value correctly.

**Comment by fbartels** [comment]
Looking at the returning values of parse_xml (and seeing that you already try to deduplicate here by piping it to uniq) I just added a sort and tail -n 1.

This for me results in 
```
+ quota=-3
+ '[' -z ']'
+ '[' '!' -z -3 ']'
+ '[' -3 -lt 0 ']'
+ quota=Unlimited
```

**Comment by cghdev** [comment]
@fbartels thanks for the fix. It is strange though on my environment (linux and mac) it was not complaining. Maybe related with bash version.
