### ISSUE TITLE
(feature request) creating nested folders and uploading local nested structures

### ISSUE THREAD

**Issue by splaisan** [cghdev/owncloud-dl#5]
Thanks for the tool, vey useful.

I would like to create nested folder structures and found that -k/--mkdir <dir> only allows creation of a single folder at a time (apparently this is a limitation from MKCOL)
In the same way, I would like to upload a local file structure with several folders and subfolders without having to create the structure first and copy each file in the right place next. We now do this using curl but I would prefer to bring all features in cloud-dl if possible

Do you see a way to implement these or could you share some hints?

Thanks in advance,

Stephane

**Comment by cghdev** [comment]
I've just implemented the creation of nested directories. Can you take a look and see if it works as expected?

Regarding creating a structure, how do you suggest passing the structure to the application? via a config file?
Alternatively, you could have the file structure on a text file and run it in a loop using the latest version of the script.
e.g:
structure.txt:
dir1/dir2
dir3/dir5/dir5
dir6
dir7/dir8/dir9/dir10

while read dirs; do cloud-dl -k $dirs; done < structure.txt

**Comment by splaisan** [comment]
cool, its works great, thanks
I had inmind to replicate a local structure to the server.
In fact we use our cloud to distribute data to collaborators and provide each of them with a folder structure containing the data.
creating first the structure with your code then uploading all files in their due location from a find -type f will do the job.
This utility will prove very useful to automatise what we currently dio file by file manually, thanks for the great tool!
I look into sending the merge request after some reading.

Best
S

**Comment by splaisan** [comment]
I added a function to mirror a folder structure that uses your improved _mkdir and seems to work for me. best
